# Generated by Django 3.0.8 on 2020-08-19 09:41

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200720_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='vizyon',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
