# Generated by Django 3.0.8 on 2020-08-19 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_setting_vizyon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='vizyon',
        ),
    ]
