# Generated by Django 3.0.8 on 2020-08-18 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='rate',
        ),
    ]
