# Generated by Django 3.0.8 on 2020-08-18 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_remove_comment_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
